[versions]
agp = "8.5.1"
gradle = "8.1.4"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }