name: Build DEX

on:
  push:
    paths:
      - 'plugin/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'plugin/**'

jobs:
  build-dex:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Build DEX file
        working-directory: plugin
        run: ./gradlew build-dex

      - name: Upload DEX artifact
        uses: actions/upload-artifact@v4
        with:
          name: classes-dex
          path: plugin/build/classes.dex
